name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        package: [vue-translate, unplugin-vue-translate]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: packages/${{ matrix.package }}/package-lock.json

      - name: Install dependencies
        run: |
          cd packages/${{ matrix.package }}
          npm ci

      - name: TypeScript check
        run: |
          cd packages/${{ matrix.package }}
          npx tsc --noEmit

      - name: Build
        run: |
          cd packages/${{ matrix.package }}
          npm run build

      - name: Test
        run: |
          cd packages/${{ matrix.package }}
          npm test
