name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: 
          - name: vue-translate
            npm_name: '@hakuna/vue-translate'
          - name: unplugin-vue-translate
            npm_name: '@hakuna/unplugin-vue-translate'
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install, build and publish ${{ matrix.package.npm_name }}
        run: |
          cd packages/${{ matrix.package.name }}
          npm ci
          npx tsc --noEmit
          npm run build
          npm run test
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          npm pkg set name="${{ matrix.package.npm_name }}"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}